name: package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "first line"
          
      - name: Build for ${{ matrix.os }}
        run: |
          cargo build --release 
          mv ./target/release/plutus-rustus ./target/release/plutus-rustus_${{ runner.os }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          files: |
            ./target/release/plutus-rustus_${{ runner.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload to dufs
        run: |
          curl -T ./target/release/plutus-rustus_${{ runner.os }}  ${{ secrets.DUFS_URL }}/plutus-rustus/release/plutus-rustus_${{ runner.os }}
          #  --user ${{ secrets.DUFS_TOKEN }}
